[workspace]

members = [
    "mla",
    "ed25519_parser",
    "mlar",
    "mla-fuzz-afl",
]

[profile.release]
opt-level = 'z'     # Optimize for size.
lto = true          # Enable Link Time Optimization
