[package]
name = "mla-fuzz-afl"
version = "0.1.0"
authors = ["Camille Mougey <camille.mougey@ssi.gouv.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
afl = "0"
bincode = "~1.2"
serde = { version = "1", features = ["derive"] }
ed25519_parser = { path = "../ed25519_parser" }
mla = { path = "../mla" }
