name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build AFL
      run: cargo install afl && cargo afl build
    - name: Build
      run: cargo build --release --all-features --verbose
    - name: Run tests
      run: cargo test --release --verbose
