name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]   

env:
  CARGO_TERM_COLOR: always

jobs:
  
  # For some reasons, matrix cannot be used in "uses" statement, so duplicate it
  build-arm64:
    runs-on: ubuntu-latest

    steps:
    - run: docker run --rm --privileged multiarch/qemu-user-static:register --reset
    
    - uses: docker://multiarch/ubuntu-core:arm64-bionic 
      with:
        args: "uname -a"

    - uses: actions/checkout@v1
      
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu
    
    - name: Install dependencies
      run: sudo apt-get install gcc-aarch64-linux-gnu
    
    - name: Cross-build
      env:
        RUSTFLAGS: -C linker=aarch64-linux-gnu-gcc 
      run: cargo build --target aarch64-unknown-linux-gnu --all --release --exclude mla-fuzz-afl --verbose
    
    - name: Cross-build tests
      env:
        RUSTFLAGS: -C linker=aarch64-linux-gnu-gcc 
      run: cargo test --no-run --target aarch64-unknown-linux-gnu --all --release --exclude mla-fuzz-afl --verbose
      
    - name: Backup Cargo cache for later use
      run: echo ~/.cargo/registry && mv ~/.cargo/registry /home/runner/work/_temp/_github_home/registry_cache
    
    - name: DEBUG
      run: pwd && ls -ahl && ls -ahl ~/.cargo
    
    - uses: docker://multiarch/ubuntu-core:arm64-bionic
      with:
        args: >
          bash -c
          "set -x &&
          echo 'Install rust components' &&
          apt-get update &&
          apt-get install -y curl llvm build-essential &&
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o /tmp/install.sh &&
          chmod +x /tmp/install.sh &&
          /tmp/install.sh -y &&
          echo 'Current toolchain:' &&
          source $HOME/.cargo/env &&
          rustup show &&
          echo 'Get back cache' &&
          mkdir -p /home/runner/work/MLA/MLA &&
          mv ./target /home/runner/work/MLA/MLA &&
          pwd && ls -ahl && ls -ahl target/ && ls -ahl ~/.cargo && mv ~/registry_cache ~/.cargo/registry &&
          echo 'Launch tests' &&
          CARGO_BUILD_TARGET_DIR=/home/runner/work/MLA/MLA/target/aarch64-unknown-linux-gnu cargo test --frozen --release --verbose --all --exclude mla-fuzz-afl --target aarch64-unknown-linux-gnu"

