name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: docker run --rm --privileged multiarch/qemu-user-static:register --reset

    - uses: docker://arm64v8/rust:latest
      with:
        args: 'uname -a'

    - uses: actions/checkout@v1
    
    - uses: docker://arm64v8/rust:latest
      with:
        args: >
          bash -c
          "ls &&
          cargo build --release --verbose --all --exclude mla-fuzz-afl &&
          cargo test --release --verbose --all --exclude mla-fuzz-afl"
