name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install dependencies
      run: sudo apt-get install llvm
    - name: Install cargo afl
      run: cargo install afl
    - name: Build
      run: cargo build --release --all-features --verbose
    - name: Test AFL build
      run: cargo afl build
    - name: Run tests
      run: cargo test --release --verbose
  
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - name: Check format
        run: cargo fmt --all -- --check
