name: Build & test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        build: [linux, macos, windows]
        include:
          - build: linux
            os: ubuntu-latest
          - build: macos
            os: macos-latest
          - build: windows
            os: windows-latest
            extension: .exe

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build
      env:
        RUSTFLAGS: -D warnings
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features --all --exclude mla-fuzz-afl --verbose
    - name: Run tests
      run: cargo test --all --exclude mla-fuzz-afl --release --verbose
    - name: Upload resulting 'mlar'
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.build }}
        path: ./target/release/mlar${{ matrix.extension }}

  afl-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install dependencies
        run: sudo apt-get install llvm
      - name: Install cargo-afl binary crate
        uses: actions-rs/install@v0.1
        with:
          crate: afl
          version: latest
          use-tool-cache: true
      - name: Test AFL build
        run: cargo afl build

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - name: Check format
        run: cargo fmt --all -- --check

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Security audit
        uses: actions-rs/audit-check@v1
        with:
         token: ${{ secrets.GITHUB_TOKEN }}
